### PR TITLE
Add Nav Drawer Content for Nav View

### PR DESCRIPTION
**Pull request by chuckh**
This adds to Nav View the following:
1. Nav Drawer Title 
1. Nav Drawer Menu Items
1. paper-toolbar to drawer nav 
1. Content Title
1. Increases height of drawer nav toolbar
1. Changes background color of drawer nav toolbar
1. box-shadow to drawer nav
## Screenshot

image

### CODE REVIEW

**Comment by notwaldorf** [comment]
@frankiefu Frankie, do you mind taking a look at this?

**Comment by chuckh** [comment]
ping @frankiefu.

**Comment by frankiefu** [comment]
Sorry about the delay.  Good work on making it to have more content.  I will need to get it reviewed by the designer cause I think they actually want the nav to have no content, and make sure to be consistent with the other templates.

**Comment by chuckh** [comment]
@frankiefu np. I added some content so it will be clearer for new users of where nav, titles and content go.  I did this template to start the discussion. If we move forward with these changes then the other templates should be updated similarly.

**Comment by chuckh** [comment]
@frankiefu did the designer give any feedback?

**Comment by frankiefu** [comment]
Sorry @chuckh, still working on it.  We are also working potentially having different structures and trying to come up with more app templates e.g. using `paper-scroll-header-panel`.  I will keep you posted.

**Comment by chuckh** [comment]
@frankiefu sounds good. You might consider having one of the app layouts correspond to Polymer Starter Kit layout.  Also I am working on a pull request for PSK to use `paper-scroll-header-panel.

**Comment by chuckh** [comment]
@frankiefu any news on this?

**Comment by cdata** [comment]
I have pinged @frankiefu to take a look.

**Comment by frankiefu** [comment]
We are working on the new [app-layout](https://github.com/PolymerLabs/app-layout) project which will replace this with its own templates here: https://github.com/PolymerLabs/app-layout/tree/master/templates

**Pull request closed without merging**
